"""create tables

Revision ID: f0eda0fe629d
Revises: 7d8d34005d45
Create Date: 2025-01-24 09:58:28.561022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0eda0fe629d'
down_revision = '7d8d34005d45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprovacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('template_aprovacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['template_aprovacao_id'], ['templates_aprovacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aprovacao_id'), 'aprovacao', ['id'], unique=False)
    op.create_table('aprovador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates_aprovacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aprovador_id'), 'aprovador', ['id'], unique=False)
    op.create_table('documento_conteudo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conteudo', sa.String(), nullable=True),
    sa.Column('versao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_conteudo_id'), 'documento_conteudo', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('template_aprovacao_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('notificacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conteudo_id'], ['documento_conteudo.id'], ),
    sa.ForeignKeyConstraint(['notificacao_id'], ['notificacoes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['template_aprovacao_id'], ['templates_aprovacao.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_nome'), 'documentos', ['nome'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('conteudo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conteudo_id'], ['documento_conteudo.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.create_index(op.f('ix_notificacoes_texto'), 'notificacoes', ['texto'], unique=False)
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('permissao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_aprovador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.ForeignKeyConstraint(['usuario_aprovador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfis_id'), 'perfis', ['id'], unique=False)
    op.create_index(op.f('ix_perfis_nome'), 'perfis', ['nome'], unique=False)
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissao_id'), 'permissao', ['id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_id'), 'status', ['id'], unique=False)
    op.create_index(op.f('ix_status_nome'), 'status', ['nome'], unique=False)
    op.create_table('templates_aprovacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('aprovacao_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('aprovador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprovacao_id'], ['aprovacao.id'], ),
    sa.ForeignKeyConstraint(['aprovador_id'], ['aprovador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_aprovacao_id'), 'templates_aprovacao', ['id'], unique=False)
    op.create_index(op.f('ix_templates_aprovacao_nome'), 'templates_aprovacao', ['nome'], unique=False)
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_id'), 'tipo', ['id'], unique=False)
    op.create_index(op.f('ix_tipo_nome'), 'tipo', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hash_senha', sa.String(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('aprovador_flag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.drop_index('ix_book_id', table_name='book')
    op.drop_index('ix_book_name', table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_name', 'book', ['name'], unique=False)
    op.create_index('ix_book_id', 'book', ['id'], unique=False)
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipo_nome'), table_name='tipo')
    op.drop_index(op.f('ix_tipo_id'), table_name='tipo')
    op.drop_table('tipo')
    op.drop_index(op.f('ix_templates_aprovacao_nome'), table_name='templates_aprovacao')
    op.drop_index(op.f('ix_templates_aprovacao_id'), table_name='templates_aprovacao')
    op.drop_table('templates_aprovacao')
    op.drop_index(op.f('ix_status_nome'), table_name='status')
    op.drop_index(op.f('ix_status_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_permissao_id'), table_name='permissao')
    op.drop_table('permissao')
    op.drop_index(op.f('ix_perfis_nome'), table_name='perfis')
    op.drop_index(op.f('ix_perfis_id'), table_name='perfis')
    op.drop_table('perfis')
    op.drop_index(op.f('ix_notificacoes_texto'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_documentos_nome'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_documento_conteudo_id'), table_name='documento_conteudo')
    op.drop_table('documento_conteudo')
    op.drop_index(op.f('ix_aprovador_id'), table_name='aprovador')
    op.drop_table('aprovador')
    op.drop_index(op.f('ix_aprovacao_id'), table_name='aprovacao')
    op.drop_table('aprovacao')
    # ### end Alembic commands ###
